#!/bin/bash
  
job_id=$1

echo "sstat命令用于查看正在运行的作业的资源使用情况"
sstat -a --format="JobId,Pids,AveCPU,AveRSS,MaxRSS" $job_id

# sacct命令用于查看已完成作业的资源使用情况
echo "sacct命令用于查看已完成作业的资源使用情况"
sacct --format="JobId,Elapsed,CPUTime,CPUTimeRAW,AveCPU,TotalCPU,UserCPU,SystemCPU,AveRSS,MaxRSS" -j $job_id