#!/usr/bin/env python3

import numpy as np

H_number = int(input("请输入氢原子的个数："))

Lu_atom_weight = 174.97
N_atom_weight  = 14.007
H_atom_weight  = 1.008

H_weight  = H_atom_weight * H_number

ratio = np.linspace(0.008, 0.009, 2)

print("N元素在Lu-N-H中占据的总质量大约为:0.008-0.009")
for Lu_number in np.arange(1,5):
    N_number = ratio*(Lu_atom_weight*Lu_number + H_atom_weight*H_number) / (N_atom_weight*(1-ratio))
    Lu_N_ratio = Lu_number // N_number
    print("Lu:N的可能比例为", Lu_N_ratio[0], Lu_N_ratio[1])