#!/bin/bash

# 运行 squeue 一次并存储输出
# squeue_output=$(squeue -h --format '%A    %t    %R    %M    %Z     %s' | grep mayuan)

squeue_output=$(squeue -h --format '%A    %t    %R    %M    %Z' | grep mayuan)

echo "running"
echo "$squeue_output" | grep " R "

echo "waiting"
echo "$squeue_output" | grep " PD "

# 提交总任务数
echo -n '提交总任务数: '
echo "$squeue_output" | wc -l
