#!/bin/bash

echo "

vasp_main.py -i CONTCAR -j slurm -p PRESS relax -m mode=rv4 execmd='mpirun -np 48' ismear=0 sigma=0.01 ediff=1e-8 ediffg=-0.001 encut=900 kspacing=0.188 queue=lhy

vasp_main.py -i CONTCAR -j slurm -p PRESS -w 100 relax -m mode=rv4 execmd='mpirun -np 48' ismear=0 sigma=0.01 ediff=1e-8 ediffg=-0.001 encut=900 kspacing=0.188 queue=lhy

vasp_main.py -i CONTCAR -j slurm -w 100-eletron  eletron -m mode='scf eledos eband' execmd='mpirun -np 48' encut=900 ediff=1e-8 ediffg=-0.001 kspacing=0.188 ismear=0 sigma=0.02  queue=lhy

vasp_main.py -i CONTCAR -j slurm -w d111 phono -m supercell='1 1 1' kspacing=0.18 mode=disp execmd=48 ismear=1 encut=800 ediff=1E-08 ediffg=-0.001 lreal=.FALSE. queue=lhy execmd='mpirun -np 48'

vasp_main.py -i POSCAR -j bash data -m mode=dispphdos supercell='2 2 2' tmin=0 tmax=4000 tstep=100

vasp_main.py -i POSCAR -j bash data -m mode=dispband supercell='2 2 2'

qe_main.py -i CONTCAR -j slurm -p PRESS -w . relax -m mode=relax-vc kpoints_dense="l m n" conv_thr=1.0d-8 execmd='mpirun -np 48' ecutwfc=80 ecutrho=960 degauss=0.02 npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS prepare -m mode=preparescf ecutwfc=80 ecutrho=960 degauss=0.02 qpoints='l m n' execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS prepare -m mode=prepareall ecutwfc=80 ecutrho=960 qpoints='l m n'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS scf -m mode=scffit ecutwfc=80 ecutrho=960 kpoints_dense='20 20 16'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS scf -m mode=scf ecutwfc=80 ecutrho=960 kpoints_sparse='10 10 8'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j bash phono -m mode=nosplit dyn0_flag=True execmd='' queue=lhy qpoints='l m n'

qe_main.py -i CONTCAR -j slurm phono -m mode=split_assignQ degauss=0.02 ecutwfc=80 ecutrho=960  execmd='mpirun -np 48' npool=4

qe_main.py -i CONTCAR -j slurm phono -m mode=split_dyn0    degauss=0.02 ecutwfc=80 ecutrho=960  execmd='mpirun -np 48' npool=4

qe_main.py -i CONTCAR -j bash phono -m mode=q2r execmd='' el_ph_nsigma=10 queue=lhy

qe_main.py -i CONTCAR -j bash phono -m mode=merge el_ph_nsigma=10 execmd=''

qe_main.py -i CONTCAR -j bash phono -m mode=phonodos execmd='mpirun -np 2' npool=1 queue=local qpoints='10 10 8' ndos=500 el_ph_nsigma=10

qe_main.py -i CONTCAR -j bash phono -m mode=phonodosdata execmd='' queue=local
qe_main.py -i CONTCAR -j bash phono -m mode=gibbsvb execmd='' queue=local

qe_main.py -i CONTCAR -j bash phono -m mode=matdyn qpoints='8 8 8' execmd='mpirun -np 2' npool=1 queue=local qinserted=50

qe_main.py -i CONTCAR -j bash phono -m mode=phonobanddata execmd=''


qe_main.py -i CONTCAR -j bash sc -m mode=Tc execmd='' npool=1 queue=local temperature_steps=100 a2fdos=True alpha2fdat=False broaden=0.5 smearing_method=1  gauss=0.035 gaussid=7

qe_main.py -i CONTCAR -j slurm scf -m mode=nscf ecutwfc=80 ecutrho=960 kpoints_sparse='48 48 48'  degauss=0.02 execmd='srun --mpi=pmi2' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm eletron -m mode=eletdos execmd='' npool=1 queue=local kpoints_dense='48 48 48'

for i in {1..18}; do cd \$i; sbatch s5_PhAssignQ.sh; cd ..; done
for i in {1..18}; do cd \$i; echo \$i; pl \$i; cd ..; done
for i in {1..18}; do cd \$i; echo \$i; ls elph_dir; cd ..; done

"
