#!/bin/bash

echo "

vasp_main.py -i CONTCAR -j slurm -p PRESS relax -m mode=rv4 execmd='mpirun -np 48' ismear=0 sigma=0.01 ediff=1e-8 ediffg=-0.001 encut=900 kspacing=0.188 queue=lhy

# 批量计算多个结构的多个压强
vasp_main.py -i stdlibs -j slurm -ps '100 200 300' batchrelax -m mode=rv4 sigma=0.01 encut=900 ediff=1e-7 ediffg=-0.01 ismear=0 core=48 kspacing=0.18 queue=lhy execmd='mpirun -np 48'

vasp_main.py -i stdlibs -j slurm -ps  100          batchrelax -m mode=rv4 sigma=0.01 encut=900 ediff=1e-7 ediffg=-0.01 ismear=0 core=48 kspacing=0.18 queue=lhy execmd='mpirun -np 48'

vasp_main.py -i CONTCAR -j slurm -p PRESS -w 100 relax -m mode=rv4 execmd='mpirun -np 48' ismear=0 sigma=0.01 ediff=1e-8 ediffg=-0.001 encut=900 kspacing=0.188 queue=lhy

vasp_main.py -i CONTCAR -j slurm -w 100-eletron  eletron -m mode='scf eledos eband' execmd='mpirun -np 48' encut=900 ediff=1e-8 ediffg=-0.001 kspacing=0.188 ismear=0 sigma=0.02  queue=lhy

vasp_main.py -i CONTCAR -j slurm -w d111 phono -m supercell='1 1 1' kspacing=0.18 mode=disp execmd=48 ismear=1 encut=800 ediff=1E-08 ediffg=-0.001 lreal=.FALSE. queue=lhy execmd='mpirun -np 48'

vasp_main.py -i POSCAR -j bash data -m mode=dispphdos supercell='2 2 2' tmin=0 tmax=4000 tstep=100

vasp_main.py -i POSCAR -j bash data -m mode=dispband supercell='2 2 2'

qe_main.py -i CONTCAR -j slurm -p PRESS -w . relax -m mode=relax-vc kpoints_dense="l m n" conv_thr=1.0d-8 execmd='mpirun -np 48' ecutwfc=80 ecutrho=960 degauss=0.02 npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS prepare -m mode=preparescf ecutwfc=80 ecutrho=960 degauss=0.02               qpoints='l m n' execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS prepare -m mode=prepareall ecutwfc=80 ecutrho=960 qpoints='l m n'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS scf -m mode=scffit ecutwfc=80 ecutrho=960 kpoints_dense='20 20 16'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j slurm -p PRESS scf -m mode=scf ecutwfc=80 ecutrho=960 kpoints_sparse='10 10 8'  degauss=0.02 execmd='mpirun -np 48' npool=4 queue=lhy

qe_main.py -i CONTCAR -j bash phono -m mode=nosplit EPC_flag=True dyn0_flag=True execmd='' queue=lhy qpoints='l m n'

qe_main.py -i CONTCAR -j slurm phono -m mode=split_assignQ EPC_flag=True degauss=0.02 ecutwfc=80 ecutrho=960  execmd='mpirun -np 48' npool=4

qe_main.py -i CONTCAR -j slurm phono -m mode=split_dyn0 EPC_flag=True degauss=0.02 ecutwfc=80 ecutrho=960  execmd='mpirun -np 48' npool=4

qe_main.py -i CONTCAR -j bash phono -m mode=q2r execmd='' el_ph_nsigma=10 queue=lhy

qe_main.py -i CONTCAR -j bash phono -m mode=merge el_ph_nsigma=10 execmd=''

qe_main.py -i CONTCAR -j bash phono -m mode=phonodos execmd='mpirun -np 2' npool=1 queue=local qpoints='10 10 8' ndos=500 el_ph_nsigma=10

qe_main.py -i CONTCAR -j bash phono -m mode=phonodosdata execmd='' queue=local
qe_main.py -i CONTCAR -j bash phono -m mode=gibbsvb execmd='' queue=local

qe_main.py -i CONTCAR -j bash phono -m mode=matdyn qpoints='8 8 8' execmd='mpirun -np 2' npool=1 queue=local qinserted=50

qe_main.py -i CONTCAR -j bash phono -m mode=phonobanddata execmd=''


qe_main.py -i CONTCAR -j bash sc -m mode=Tc execmd='' npool=1 queue=local temperature_steps=100 a2fdos=True alpha2fdat=False broaden=0.5 smearing_method=1  gauss=0.035 gaussid=7


# qe能带计算
qe_main.py -i PPOSCAR -j bash -w band eletron -m mode=eleband execmd='mpirun -np 2 ' npool=1 queue=local kinserted=200 charge_density_dat='../phonon/tmp/H3S1.save/charge-density.dat' data_file_schema_xml='../phonon/tmp/H3S1.save/data-file-schema.xml'  

# 获得能带的高对称路径二维投影 
qe_main.py -i PPOSCAR -j bash eletron -m mode=hspp  execmd=''

# 特别注意nbnd的设置, 不要太高了, 不然根本算不动。
# nbnd=500

qe_main.py -i PPOSCAR -j bash eletron -m mode=elebanddata execmd='' queue=lhy

# qe态密度计算

# 适用于EPW计算前的nscf计算，这里的展开方式是高斯展宽，因为EPW要求nscf的K点是自定义坐标的，而自定义坐标的nscf不支持四面体方法
qe_main.py -i ../phonon/PPOSCAR -j bash scf -m mode=nscf ecutwfc=80 ecutrho=960 kpoints_dense='8 8 8'  degauss=0.02 execmd='mpirun -np 4' npool=4  charge_density_dat='../phonon/tmp/H3S1.save/charge-density.dat' data_file_schema_xml='../phonon/tmp/H3S1.save/data-file-schema.xml'  k_automatic=False wan=False  occupations=smearing  queue=lhy

# 四面体方法计算nscf
qe_main.py -i ../phonon/PPOSCAR -j bash scf -m mode=nscf ecutwfc=80 ecutrho=960 kpoints_dense='8 8 8'  degauss=0.02 execmd='mpirun -np 4' npool=4  charge_density_dat='../phonon/tmp/H3S1.save/charge-density.dat' data_file_schema_xml='../phonon/tmp/H3S1.save/data-file-schema.xml'  k_automatic=True   occupations=tetrahedra  queue=lhy

# 处理态密度
qe_main.py -i CONTCAR -j slurm eletron -m mode=eledosdata execmd='' npool=1 queue=local kpoints_dense='48 48 48'


for i in {1..18}; do cd \$i; sbatch s5_PhAssignQ.sh; cd ..; done
for i in {1..18}; do cd \$i; echo \$i; pl \$i; cd ..; done
for i in {1..18}; do cd \$i; echo \$i; ls elph_dir; cd ..; done

# EPW的wannir90部分计算能带
qe_main.py -i origin-PPOSCAR -j bash -w . epw -m mode=epw_energyband execmd='mpirun -np 2' npool=2 dvscf_dir='../phonon/save'  nbndsub=10  bands_skipped=5  dis_froz_min=-5 dis_froz_max=0 proj='S:p  H:s' 


# SCTK计算超导

qe_main.py -i relax.out -j bash prepare -m mode=preparescf ecutwfc=80 ecutrho=960 occupations=tetrahedra_opt qpoints='4 4 4' execmd='mpirun -np 8' npool=2 queue=lhy

qe_main.py -i relax.out -j bash phono   -m mode=nosplit    dyn0_flag=False EPC_flag=False SCTK_flag=True search_sym=.false. execmd='mpirun -np 8'  qpoints='4 4 4' queue=lhy

qe_main.py -i relax.out -j bash phono   -m mode=nosplit    dyn0_flag=False EPC_flag=True  SCTK_flag=True search_sym=.false. elph_nbnd_min=2 elph_nbnd_max=6 execmd='mpirun -np 8' npool=8  qpoints='4 4 4' queue=lhy

在稠密K网格下进行Non-SCF计算, 是qpoints的 4 倍
qe_main.py -i relax.out -j bash -w nscf_16x16x16 scf -m mode=nscf ecutwfc=80 ecutrho=960 kpoints_dense='16 16 16'  degauss=0.02 execmd='mpirun -np 8' npool=8  charge_density_dat='tmp/H3S1.save/charge-density.dat' data_file_schema_xml='tmp/H3S1.save/data-file-schema.xml'  k_automatic=True   occupations=tetrahedra_opt  queue=lhy

计算屏蔽库仑相互作用下的波函数, k点网格必须和ph.x计算电声相互作用时使用的 nq1 nq2 nq3 一样。然后运行pw.x
qe_main.py -i relax.out -j bash -w nscf_16x16x16 scf -m mode=twin ecutwfc=80 ecutrho=960 kpoints_dense='4 4 4'  degauss=0.02 execmd='mpirun -np 8' npool=8 k_automatic=False queue=lhy

计算屏蔽库仑相互作用
qe_main.py -i relax.out -j bash -w nscf_16x16x16  -l info sctk -m mode=coulomp kpoints_dense='4 4 4' execmd='mpirun -np 8' npool=8 queue=lhy
"
