#!/bin/bash
  
name=$1

# 如果name是空的，获取当前绝对路径并赋值给name
if [ -z "$name" ]; then # -z：检查字符串的长度是否为零。如果字符串的长度为零，则返回真 (true)>。
    name=$(pwd)
fi

# 运行 squeue 一次并存储输出
squeue_output=$(squeue -h --format '%A    %t    %R    %M    %Z     %s' | grep mayuan)

echo "running"
echo "$squeue_output" | grep " R "  | grep "$name"

echo "waiting"
echo "$squeue_output" | grep " PD " | grep "$name"

# 提交总任务数
echo -n '提交总任务数: '
echo "$squeue_output" | wc -l | grep "$name"
