"""
基础类模块

提供所有计算软件共享的基础类和功能。

作者：Claude
创建时间：2025-11-20
"""

from pathlib import Path
from typing import Dict, Any, Optional
from abc import ABC, abstractmethod


class BaseWorkflow(ABC):
    """
    工作流基类

    所有计算软件的workflow都应继承此类。

    Attributes
    ----------
    work_path : Path
        工作目录
    config : Dict[str, Any]
        配置字典
    """

    def __init__(self, work_path: Path, config: Dict[str, Any]):
        """
        初始化工作流

        Parameters
        ----------
        work_path : Path
            工作目录
        config : Dict[str, Any]
            配置字典
        """
        self.work_path = Path(work_path)
        self.config = config

        # 创建工作目录
        self.work_path.mkdir(parents=True, exist_ok=True)

    @abstractmethod
    def prepare_inputs(self):
        """准备输入文件（子类必须实现）"""
        pass

    @abstractmethod
    def run(self):
        """运行计算（子类必须实现）"""
        pass

    def cleanup(self):
        """
        清理临时文件（子类可选实现）

        默认实现：删除tmp目录
        """
        tmp_dir = self.work_path / 'tmp'
        if tmp_dir.exists():
            import shutil
            shutil.rmtree(tmp_dir)


class BaseInputWriter(ABC):
    """
    输入文件写入器基类

    所有输入文件生成器都应继承此类。
    """

    def __init__(self, work_path: Path, params: Dict[str, Any]):
        """
        初始化写入器

        Parameters
        ----------
        work_path : Path
            工作目录
        params : Dict[str, Any]
            参数字典
        """
        self.work_path = Path(work_path)
        self.params = params

    @abstractmethod
    def write(self, filename: str):
        """
        写入输入文件

        Parameters
        ----------
        filename : str
            输出文件名
        """
        pass

    def _write_header(self, f, comment: str = ""):
        """
        写入文件头部注释

        Parameters
        ----------
        f : file object
            文件对象
        comment : str
            注释内容
        """
        if comment:
            f.write(f"# {comment}\n")
            f.write(f"# Generated by computational toolkit\n")
            f.write(f"# {'-' * 50}\n\n")


class BaseOutputReader(ABC):
    """
    输出文件读取器基类

    所有输出文件解析器都应继承此类。
    """

    def __init__(self, output_file: Path):
        """
        初始化读取器

        Parameters
        ----------
        output_file : Path
            输出文件路径
        """
        self.output_file = Path(output_file)

        if not self.output_file.exists():
            raise FileNotFoundError(f"输出文件不存在: {self.output_file}")

    @abstractmethod
    def parse(self) -> Dict[str, Any]:
        """
        解析输出文件

        Returns
        -------
        Dict[str, Any]
            解析结果字典
        """
        pass

    def _read_file(self) -> str:
        """
        读取文件内容

        Returns
        -------
        str
            文件内容
        """
        with open(self.output_file, 'r', encoding='utf-8', errors='ignore') as f:
            return f.read()

    def _read_lines(self) -> list:
        """
        读取文件行列表

        Returns
        -------
        list
            行列表
        """
        with open(self.output_file, 'r', encoding='utf-8', errors='ignore') as f:
            return f.readlines()


class StructureFile:
    """
    结构文件基类

    用于读取和处理不同格式的结构文件（POSCAR/CIF/XSF等）。
    """

    def __init__(self, file_path: Path):
        """
        初始化结构文件

        Parameters
        ----------
        file_path : Path
            结构文件路径
        """
        self.file_path = Path(file_path)

        if not self.file_path.exists():
            raise FileNotFoundError(f"结构文件不存在: {self.file_path}")

    @classmethod
    def from_format(cls, file_path: Path, format_type: str):
        """
        根据格式类型创建结构对象

        Parameters
        ----------
        file_path : Path
            文件路径
        format_type : str
            格式类型 ('poscar', 'cif', 'xsf', etc.)

        Returns
        -------
        StructureFile
            结构文件对象
        """
        # 这里可以根据format_type返回不同的子类
        return cls(file_path)
